// Code generated by onos-ric-generate. DO NOT EDIT.

package {{ .Interface.Package.Name }}

import (
	messagestore "github.com/onosproject/onos-ric/pkg/store/message"
	"io"
	{{ .DataType.Package.Alias }} {{ .DataType.Package.Path | quote }}
)

type ID string

// Revision is a message revision
type Revision struct {
	Term Term
	Timestamp Timestamp
}

type Term uint64

type Timestamp uint64

// {{ .Interface.Type.Name }} is interface for store
type {{ .Interface.Type.Name }} interface {
	io.Closer

	// Gets a message based on a given ID
	Get(ID, ...GetOption) (*{{ .DataType.Package.Alias }}.{{ .DataType.Name }}, error)

	// Puts a message to the store
	Put(*{{ .DataType.Package.Alias }}.{{ .DataType.Name }}) error

	// Removes a message from the store
	Delete(ID, ...DeleteOption) error

	// List all of the last up to date messages
	List(ch chan<- {{ .DataType.Package.Alias }}.{{ .DataType.Name }}) error

	// Watch watches messages
	Watch(ch chan<- {{ .DataType.Package.Alias }}.{{ .DataType.Name }}, opts ...WatchOption) error

	// Clear deletes all messages from the store
	Clear() error
}

// GetOption is a message store get option
type GetOption messagestore.GetOption

// WithRevision returns a GetOption that ensures the retrieved entry is newer than the given revision
func WithRevision(revision Revision) GetOption {
	return messagestore.WithRevision(toMessageRevision(revision))
}

// DeleteOption is a message store delete option
type DeleteOption messagestore.DeleteOption

// IfRevision returns a delete option that deletes the message only if its revision matches the given revision
func IfRevision(revision Revision) DeleteOption {
	return messagestore.IfRevision(toMessageRevision(revision))
}

// WatchOption is a store watch option
type WatchOption messagestore.WatchOption

// WithReplay returns a watch option that replays existing messages
func WithReplay() WatchOption {
	return messagestore.WithReplay()
}
