// Code generated by onos-ric-generate. DO NOT EDIT.

package updates

import (
	e2ap "github.com/onosproject/onos-ric/api/sb/e2ap"
	messagestore "github.com/onosproject/onos-ric/pkg/store/message"
	"io"
)

type PartitionKey string

type Key string

type ID struct {
	Partition PartitionKey
	Key       Key
}

// Revision is a message revision
type Revision struct {
	Term      Term
	Timestamp Timestamp
}

type Term uint64

type Timestamp uint64

// Event is a store event
type Event struct {
	// Type is the event type
	Type EventType
	// ID is the message identifier
	ID ID
	// Message is the event message
	Message e2ap.RicIndication
}

// EventType is a store event type
type EventType messagestore.EventType

const (
	EventNone   EventType = EventType(messagestore.EventNone)
	EventInsert EventType = EventType(messagestore.EventInsert)
	EventUpdate EventType = EventType(messagestore.EventUpdate)
	EventDelete EventType = EventType(messagestore.EventDelete)
)

// Store is interface for store
type Store interface {
	io.Closer

	// Gets a message based on a given ID
	Get(ID, ...GetOption) (*e2ap.RicIndication, error)

	// Puts a message to the store
	Put(ID, *e2ap.RicIndication, ...PutOption) error

	// Removes a message from the store
	Delete(ID, ...DeleteOption) error

	// List all of the last up to date messages
	List(ch chan<- e2ap.RicIndication) error

	// Watch watches the store for changes
	Watch(ch chan<- Event, opts ...WatchOption) error

	// Clear deletes all messages from the store
	Clear() error
}

// GetOption is a message store get option
type GetOption messagestore.GetOption

// WithRevision returns a GetOption that ensures the retrieved entry is newer than the given revision
func WithRevision(revision Revision) GetOption {
	return messagestore.WithRevision(toMessageRevision(revision))
}

// PutOption is a message store put option
type PutOption messagestore.PutOption

// DeleteOption is a message store delete option
type DeleteOption messagestore.DeleteOption

// IfRevision returns a delete option that deletes the message only if its revision matches the given revision
func IfRevision(revision Revision) DeleteOption {
	return messagestore.IfRevision(toMessageRevision(revision))
}

// WatchOption is a store watch option
type WatchOption messagestore.WatchOption

// WithReplay returns a watch option that replays existing messages
func WithReplay() WatchOption {
	return messagestore.WithReplay()
}
